image: maven:3-openjdk-18-slim


stages:
  - build
  - deploy_docker
  - deploy_k8s


build:
  stage: build
  only:
    - develop
  script:
    - mvn clean package
    - echo "Building stage"
  artifacts:
    paths:
      - impl/target

deploy_docker:
  image: docker:19.03.12
  stage: deploy_docker
  only:
    - develop
  before_script:
    - docker logout
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  script:
    - echo "Deploy stage begin"
    - docker build -f Dockerfile -t skillboxteam32/social-media .
    - docker push skillboxteam32/social-media
    - echo "Deploy stage end"
  artifacts:
    paths:
      - impl/target/social-service-impl-1.0.0-SNAPSHOT-exec.jar

  environment: production

deploy_prod:
  stage: deploy_k8s
  only:
    - develop
  except:
    - tags
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $PROD_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $PROD_USER@$PROD_HOST "kubectl rollout restart -n $NAMESPACE deployment $DEPLOYMENT_NAME"